Remote control
jellyfin/jellyfin-apiclient-python pull request #14
Opened 2022-08-23 19:42 UTC by Ongy

Adds new API functions to allow remote controlling another session.

Implemented for and tested with https://github.com/home-assistant/core/pull/76801#discussion_r950886699

2022-08-23 21:36 UTC, iwalton3 requested changes

2022-08-23 21:36 UTC, iwalton3 commented on jellyfin_apiclient_python/api.py
> +        return self.remote(id, "PlauPause")
Typo?
```suggestion
        return self.remote(id, "PlayPause")
```

2022-08-24 04:10 UTC, Ongy commented
Rebased for Readme.md conflict.

2022-08-24 11:31 UTC, iwalton3 approved these changes

2022-08-24 11:31 UTC, merged

2022-08-24 11:59 UTC, iwalton3 commented
https://pypi.org/project/jellyfin-apiclient-python/1.9.0/

Thanks for contributing to Home Assistant!

2022-08-24 21:19 UTC, iwalton3 commented
Looks like a broken type hint was causing some issues. Should be fixed now.

See: https://github.com/jellyfin/jellyfin-mpv-shim/issues/292

https://pypi.org/project/jellyfin-apiclient-python/1.9.1/