Amend get_next
jellyfin/jellyfin-apiclient-python pull request #51
Opened 2024-09-26 09:03 UTC by ryanbdclark

Amend the get_next function which calls /Shows/NextUp to include an optional seriesid and userid parameter. 

This will allow you to retrieve the next up just for a specific series rather than all series, as well as getting the next up for a specific user rather than being limited to the user currently logged in.

Before I go down a rabbit hole with this as I have more changes I'd like to make. What's your opinion about allowing the user to specify a userid in the request rather than always using the current logged in user? I feel as an admin user logged in I should be able to retrieve information about any user rather than just the user I am logged in as. If you can already do this and I've missed it then let me know.

2024-12-01 14:26 UTC, ryanbdclark commented
Did you have any feedback on this pull request?

2025-03-17 20:17 UTC, iwalton3 requested changes

2025-03-17 20:17 UTC, iwalton3 commented on jellyfin_apiclient_python/api.py
> +    def get_next(self, userId=None, index=None, limit=1, seriesId=None):
To ensure backwards compatibility please do not add new arguments before existing ones.

2026-05-03 19:49 UTC, iwalton3 commented
Closing this due to non-response, if still interested please re-open.

2026-05-03 19:49 UTC, closed without merging